accounts/urls.py
""" Guess number accounts urls """

from django.conf.urls import url
from django.contrib.auth import views as generic_user_views
from . import views


app_name = "accounts"

urlpatterns = [
    url(r'^login/$', views.Signin.as_view(), name='user_login'),
    url(r'^logout/$', generic_user_views.logout_then_login, name='user_logout'),
    url(r'^signup/$', views.SignUp.as_view(), name='user_signup'),
]

gnumber/urls.py
from django.conf.urls import url
from . import views


app_name = "gnumber"

urlpatterns = [
    url(r'^$', views.Index.as_view(), name='index'),
    url(r'^create/$', views.createRoom, name='create'),
    url(r'^(?P<room_id>\w+)/game/$', views.gameRoom, name='game'),
    url(r'^rank/$', views.RankView.as_view(), name='rank'),
]

pyGuestNumber/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('gnumber.urls')),
    url(r'^user/', include('accounts.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

gnumber/models.py
from django.db import models
from django.contrib.auth.models import User

class Results(models.Model):
    """ user's result """
    user = models.OneToOneField(User, unique=True, related_name='result')
    result = models.IntegerField(default=0)
    def __str__(self):
        return str(self.user)

accounts/views.py
""" extend generic forms """
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth.views import LoginView, login
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse
from django.views import View


class Signin(LoginView):
    """ extend generic login view. """
    template_name = 'registration/login.html'

    def redirectTo(self):
        """ redirect to index. """
        return HttpResponseRedirect(reverse('gnumber:index'))

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return self.redirectTo()
        return super(Signin, self).dispatch(request, *args, **kwargs)


class SignUp(View):
    """ simple  """
    def get(self, request):
        form = UserCreationForm()
        return render(request, 'registration/signup.html', locals())

    def post(self, request):
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('accounts:user_login'))

gnumber/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic, View
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import Results
from . import game


class Index(View):
    """ index view """
    template_name = "index.html"
    def get(self, request, *args, **kwargs):
        """
        Return room list
        """
        return render(request, self.template_name, {"room_list": game.listRoom(),})


class RankView(generic.ListView):
    model = Results
    template_name = "ranking.html"
    def get_context_data(self, **kwargs):
        """
        Return top 10 rank
        """
        context = super(RankView, self).get_context_data(**kwargs)
        context["ranking_list"] = Results.objects.filter(result__lte=1).order_by('-result')
        return context


@login_required
def createRoom(request):
    room_id = game.create(request.user.id)
    status = game.startGame(room_id)
    if not status:
        return render(request, 'error_message.html', {'error_message': '開局失敗'})
    return HttpResponseRedirect(reverse('gnumber:game', args=(room_id,)))


@login_required
def gameRoom(request, room_id):
    if game.roomExist(room_id) != 1:
        return render(request, 'error_message.html', {'error_message': '遊戲不存在'})
    if game.roomMemberCounter(room_id) is False:
        return render(request, 'error_message.html', {'error_message': '房間已滿'})
    if game.userExistInRoom(room_id, request.user.id) == 0:
        result, message = game.userJoin(room_id, request.user.id)
        if not result:
            return render(request, 'error_message.html', {'error_message': message})

    gameOver = False
    result = None

    if request.method == "POST":
        game.userIncre(room_id, request.user.id)
        inputNumber = request.POST['InputNumber']
        status, response = game.checkMatch(room_id, inputNumber)
        if not status:
            print(status, response)
            gameOver = True
            game.endGame(room_id)
        else:
            if int(response[0]) == 4:
                gameOver = True
                game.endGame(room_id)
                thisResult = int(game.getUserResult(room_id, request.user.id))
                if Results.objects.filter(user=request.user).exists() > 0:
                    lastRecord = get_object_or_404(Results, user=request.user)
                    if lastRecord is not None:
                        if lastRecord.result == 0 or lastRecord.result > thisResult:
                            lastRecord.result = thisResult
                            lastRecord.save()
                else:
                    createRecord = Results.objects.create(user=request.user, result=thisResult)
                    createRecord.save()
            result = "{A}A{B}B".format(A=response[0], B=response[1])
            
    
    status = game.getUsersInRoom(room_id)
    if not isinstance(status, dict):
        return render(request, 'error_message.html', {'error_message': '請輸入合法路徑'})
    outputResult = {}
    for key in status:
        outputResult[User.objects.get(id=key).username] = status.get(key)

    return render(request, 'game_room.html', {'game_status': outputResult,
                                              'guess_result': result,
                                              'game_over': gameOver})

gnumber/templates/error_message.html
{% extends "nav_base.html" %} {% block title %}系統訊息{% endblock title %} {% block body %}
<div class="container">
    <div class="middle-message">
        <h1>{{ error_message }}</h1>
    </div>
</div>
{% endblock body %}

gnumber/templates/game_room.html
{% extends "nav_base.html" %} {% block title %}遊戲房間{% endblock title %} {% block body %}
<div class="container">
    <table id="result" class="table">
        <thead>
            <tr>
                <th>玩家</th>
                <th>回合</th>
            </tr>
        </thead>
        <tbody>
            {% for user, value in game_status.items %}
            <tr>
                <td>{{ user }}</td>
                <td>{{ value }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div id="inner">
        <label class="col-form-label" for="InputNumber">請輸入 4 個 0~9 整數</label>
        <form method="POST" action=".">
            {% csrf_token %}
            <div class="form-group row">
                <div class="col-md-2">
                    <input type="text" id="InputNumber" name="InputNumber" class="form-control" placeholder="1234">
                </div>
                {% if not game_over %}
                <div class="col-md-1">
                    <button class="btn btn-primary btn-block" type="submit">確定</button>
                </div>
                {% endif %}
            </div>
        </form>
        {% if guess_result %}
        <div id="guess-result">
            <h3>{{ guess_result }}</h3>
        </div>
        {% endif %}
    </div>
</div>
{% endblock body %}

gnumber/templates/index.html
{% extends "nav_base.html" %} {% block body %}
<div class="container">
    <div class="middle-message">
        <h1>全國最大在線猜數字上線啦！</h1>
    </div>
    {% if room_list %}
    <table class="table">
        <thead class="thead-inverse">
            <tr>
                <th>房間</th>
                <th>連結</th>
            </tr>
        </thead>
        <tbody>
            {% for room in room_list %}
            <tr>
                <td>{{ room }}</td>
                <td><a href="{% url 'gnumber:game' room_id=room %}">進入</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endif %}
</div>
{% endblock body %}

gnumber/templates/nav_base.html
{% extends "base.html" %} {% block extra-style %}
{% load static %}
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'game_style.css' %}"> {% endblock extra-style %} {% block title %}全國最大在線猜數字上線啦！{% endblock title %} {% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="/">猜數字</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'gnumber:create' %}">開局</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'gnumber:rank' %}">英雄榜</a>
                </li>
            </ul>
            {% if request.user.is_authenticated %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="http://example.com" id="user-dropdown" data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false"><i class="material-icons">account_circle</i></a>
                    <div class="dropdown-menu" aria-labelledby="user-dropdown">
                        <p class="dropdown-item disable">{{ request.user }}</p>
                        <a class="dropdown-item" href="{% url 'accounts:user_logout' %}">登出</a>
                    </div>
                </li>
            </ul>
            {% else %}
            <a href="{% url 'accounts:user_login' %}">登入</a> &nbsp;或&nbsp;
            <a href="{% url 'accounts:user_signup' %}">註冊</a> {% endif %}
        </div>
    </div>
</nav>
{% block body %}{% endblock body %} {% load static %}
<script src="{% static 'jquery.slim.min.js' %}"></script>
<script src="{% static 'popper.min.js' %}"></script>
<script src="{% static 'bootstrap.min.js' %}"></script>
{% endblock content %}

gnumber/templates/ranking.html
{% extends "nav_base.html" %}
{% block body %}
    <table class="table">
        <thead>
            <tr>
                <th>排名</th>
                <th>ID</th>
                <th>回合</th>
            </tr>
        </thead>
        <tbody>
        {% if ranking_list %}
        {% for results_cell in ranking_list %}
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ results_cell.user }}</td>
            <td>{{ results_cell.result }}</td>
        {% endfor %}
        {% endif %}
        </tbody>
    </table>
{% endblock body %}

templates/base.html
<!DOCTYPE html>
<html lang="zh-Hant">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        {% block extra-meta %}{% endblock extra-meta %}
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
        {% block extra-style %}{% endblock extra-style %}
        <title>{% block title %}{% endblock title %}</title>
    </head>
    <body>
        {% block content %}
        {% endblock content %}
    </body>
</html>